import { createSlice } from '@reduxjs/toolkit'

const initial = {
  Data: [
    {
      id: 1,
      title: 'Wireless Bluetooth Headphones',
      price: 59.99,
      rating: 4.4,
      reviewsCount: 1380,
      category: 'Electronics',
      items: [
        {
          name: 'Cleaning Tools',
          image: 'https://picsum.photos/150/150?random=6',
        },
        {
          name: 'Home Storage',
          image: 'https://picsum.photos/150/150?random=7',
        },
        { name: 'Home Decor', image: 'https://picsum.photos/150/150?random=8' },
        { name: 'Bedding', image: 'https://picsum.photos/150/150?random=9' },
      ],
      description:
        'High-quality over-ear Bluetooth headphones with noise cancellation.',
      prime: true,
      discount: 10,
    },
    {
      id: 2,
      title: 'Smart Fitness Watch',
      price: 89.99,
      rating: 4.2,
      reviewsCount: 1120,
      category: 'Electronics',
      items: [
        {
          name: 'Jeans under $50',
          image: 'https://picsum.photos/150/150?random=2',
        },
        {
          name: 'Tops under $25',
          image: 'https://picsum.photos/150/150?random=3',
        },
        {
          name: 'Dresses under $30',
          image: 'https://picsum.photos/150/150?random=4',
        },
        {
          name: 'Shoes under $50',
          image: 'https://picsum.photos/150/150?random=5',
        },
      ],
      description:
        'Track your steps, heart rate, and sleep with this sleek smartwatch.',
      prime: true,
      discount: 15,
    },
    {
      id: 3,
      title: "Men's Casual Sneakers",
      price: 45.99,
      rating: 4.1,
      reviewsCount: 720,
      items: [
        {
          name: 'Kitchen & Dining',
          image: 'https://picsum.photos/150/150?random=10',
        },
        {
          name: 'Home Improvement',
          image: 'https://picsum.photos/150/150?random=11',
        },
        { name: 'Décor', image: 'https://picsum.photos/150/150?random=12' },
        {
          name: 'Bedding & Bath',
          image: 'https://picsum.photos/150/150?random=13',
        },
      ],
      category: 'Fashion',
      image: 'https://picsum.photos/200?random=3',
      description: 'Comfortable and stylish sneakers for everyday wear.',
      prime: false,
      discount: 5,
    },
    {
      id: 4,
      title: '4K Ultra HD Smart TV 55-inch',
      price: 499.99,
      rating: 4.7,
      reviewsCount: 2500,
      category: 'Electronics',
      image: 'https://picsum.photos/200?random=4',
      description:
        'Enjoy a cinematic viewing experience with vibrant colors and 4K clarity.',
      prime: true,
      discount: 20,
    },
    {
      id: 5,
      title: 'Ergonomic Office Chair',
      price: 129.99,
      rating: 4.5,
      reviewsCount: 830,
      category: 'Home & Office',
      image: 'https://picsum.photos/200?random=5',
      description:
        'Adjustable office chair with lumbar support and breathable mesh.',
      prime: true,
      discount: 12,
    },
    {
      id: 6,
      title: 'Stainless Steel Water Bottle',
      price: 18.99,
      rating: 4.6,
      reviewsCount: 2400,
      category: 'Outdoors',
      image: 'https://picsum.photos/200?random=6',
      description: 'Keeps your drinks cold for 24 hours and hot for 12.',
      prime: true,
      discount: 8,
    },
    {
      id: 7,
      title: 'Noise Cancelling Earbuds',
      price: 74.99,
      rating: 4.3,
      reviewsCount: 1900,
      category: 'Electronics',
      image: 'https://picsum.photos/200?random=7',
      description: 'Compact and lightweight earbuds with immersive sound.',
      prime: true,
      discount: 10,
    },
    {
      id: 8,
      title: 'Men’s Leather Wallet',
      price: 24.99,
      rating: 4.5,
      reviewsCount: 540,
      category: 'Fashion',
      image: 'https://picsum.photos/200?random=8',
      description: 'Durable genuine leather wallet with multiple card slots.',
      prime: false,
      discount: 7,
    },
    {
      id: 9,
      title: 'Wireless Gaming Mouse',
      price: 39.99,
      rating: 4.4,
      reviewsCount: 890,
      category: 'Electronics',
      image: 'https://picsum.photos/200?random=9',
      description:
        'Ergonomic gaming mouse with RGB lighting and adjustable DPI.',
      prime: true,
      discount: 10,
    },
    {
      id: 10,
      title: 'Cotton Queen Bedsheet Set',
      price: 35.99,
      rating: 4.2,
      reviewsCount: 480,
      category: 'Home & Office',
      image: 'https://picsum.photos/200?random=10',
      description: 'Soft, breathable cotton bedsheet with two pillow covers.',
      prime: false,
      discount: 6,
    },

    {
      id: 11,
      title: 'Stainless Steel Cookware Set',
      price: 99.99,
      rating: 4.6,
      reviewsCount: 620,
      category: 'Home & Kitchen',
      image: 'https://picsum.photos/200?random=11',
      description:
        '10-piece stainless steel cookware set suitable for all cooktops.',
      prime: true,
      discount: 15,
    },
    {
      id: 12,
      title: "Women's Denim Jacket",
      price: 49.99,
      rating: 4.3,
      reviewsCount: 310,
      category: 'Fashion',
      image: 'https://picsum.photos/200?random=12',
      description: 'Classic denim jacket perfect for layering in any season.',
      prime: true,
      discount: 10,
    },
    {
      id: 13,
      title: 'Gaming Mechanical Keyboard',
      price: 89.99,
      rating: 4.7,
      reviewsCount: 1750,
      category: 'Electronics',
      image: 'https://picsum.photos/200?random=13',
      description:
        'RGB mechanical keyboard with blue switches for responsive gameplay.',
      prime: true,
      discount: 12,
    },
    {
      id: 14,
      title: 'Portable Power Bank 20000mAh',
      price: 39.99,
      rating: 4.5,
      reviewsCount: 980,
      category: 'Electronics',
      image: 'https://picsum.photos/200?random=14',
      description: 'Fast charging power bank with dual USB outputs.',
      prime: true,
      discount: 8,
    },
    {
      id: 15,
      title: "Men's Analog Wrist Watch",
      price: 69.99,
      rating: 4.2,
      reviewsCount: 430,
      category: 'Fashion',
      image: 'https://picsum.photos/200?random=15',
      description:
        'Elegant wristwatch with leather strap and water resistance.',
      prime: false,
      discount: 5,
    },
    {
      id: 16,
      title: 'Electric Kettle 1.8L',
      price: 29.99,
      rating: 4.4,
      reviewsCount: 600,
      category: 'Home & Kitchen',
      image: 'https://picsum.photos/200?random=16',
      description:
        'Quick boil kettle with auto shut-off and stainless steel body.',
      prime: true,
      discount: 10,
    },
    {
      id: 17,
      title: 'Adjustable Dumbbell Set 20kg',
      price: 109.99,
      rating: 4.6,
      reviewsCount: 780,
      category: 'Sports & Fitness',
      image: 'https://picsum.photos/200?random=17',
      description: 'Space-saving dumbbell set ideal for home workouts.',
      prime: true,
      discount: 20,
    },
    {
      id: 18,
      title: 'Laptop Backpack with USB Port',
      price: 44.99,
      rating: 4.5,
      reviewsCount: 980,
      category: 'Accessories',
      image: 'https://picsum.photos/200?random=18',
      description:
        'Water-resistant backpack with USB charging port and laptop sleeve.',
      prime: true,
      discount: 12,
    },
    {
      id: 19,
      title: 'Air Fryer 5L',
      price: 89.99,
      rating: 4.6,
      reviewsCount: 1240,
      category: 'Home & Kitchen',
      image: 'https://picsum.photos/200?random=19',
      description:
        'Cook crispy fried food with little to no oil using this air fryer.',
      prime: true,
      discount: 18,
    },
    {
      id: 20,
      title: 'Men’s Running Shorts',
      price: 24.99,
      rating: 4.3,
      reviewsCount: 300,
      category: 'Fashion',
      image: 'https://picsum.photos/200?random=20',
      description: 'Lightweight and breathable shorts for running or gym.',
      prime: false,
      discount: 6,
    },
    {
      id: 21,
      title: 'Cordless Vacuum Cleaner',
      price: 139.99,
      rating: 4.4,
      reviewsCount: 870,
      category: 'Home Appliances',
      image: 'https://picsum.photos/200?random=21',
      description:
        'Lightweight cordless vacuum for quick cleaning around the house.',
      prime: true,
      discount: 15,
    },
    {
      id: 22,
      title: 'Portable Bluetooth Speaker',
      price: 34.99,
      rating: 4.5,
      reviewsCount: 1600,
      category: 'Electronics',
      image: 'https://picsum.photos/200?random=22',
      description:
        'Compact waterproof speaker with deep bass and long battery life.',
      prime: true,
      discount: 10,
    },
    {
      id: 23,
      title: 'Men’s Hoodie Sweatshirt',
      price: 39.99,
      rating: 4.2,
      reviewsCount: 540,
      category: 'Fashion',
      image: 'https://picsum.photos/200?random=23',
      description: 'Soft cotton hoodie for casual everyday wear.',
      prime: true,
      discount: 5,
    },
    {
      id: 24,
      title: 'Smart Home Security Camera',
      price: 79.99,
      rating: 4.3,
      reviewsCount: 850,
      category: 'Electronics',
      image: 'https://picsum.photos/200?random=24',
      description:
        '1080p Wi-Fi camera with motion detection and two-way audio.',
      prime: true,
      discount: 10,
    },
    {
      id: 25,
      title: 'Non-Stick Frying Pan 30cm',
      price: 29.99,
      rating: 4.4,
      reviewsCount: 420,
      category: 'Home & Kitchen',
      image: 'https://picsum.photos/200?random=25',
      description: 'Durable non-stick frying pan suitable for all stove types.',
      prime: true,
      discount: 8,
    },
    {
      id: 26,
      title: 'Wireless Keyboard and Mouse Combo',
      price: 49.99,
      rating: 4.3,
      reviewsCount: 950,
      category: 'Electronics',
      image: 'https://picsum.photos/200?random=26',
      description:
        'Ergonomic wireless keyboard and mouse for seamless productivity.',
      prime: true,
      discount: 9,
    },
    {
      id: 27,
      title: 'Women’s Handbag Set',
      price: 59.99,
      rating: 4.4,
      reviewsCount: 370,
      category: 'Fashion',
      image: 'https://picsum.photos/200?random=27',
      description:
        'Elegant handbag set with matching clutch and shoulder strap.',
      prime: false,
      discount: 10,
    },
    {
      id: 28,
      title: 'Wireless Charging Pad',
      price: 19.99,
      rating: 4.2,
      reviewsCount: 740,
      category: 'Electronics',
      image: 'https://picsum.photos/200?random=28',
      description:
        'Fast wireless charger compatible with all Qi-enabled devices.',
      prime: true,
      discount: 7,
    },
    {
      id: 29,
      title: 'Gaming Chair with Lumbar Support',
      price: 189.99,
      rating: 4.5,
      reviewsCount: 920,
      category: 'Home & Office',
      image: 'https://picsum.photos/200?random=29',
      description:
        'Comfortable gaming chair with adjustable armrests and tilt function.',
      prime: true,
      discount: 18,
    },
    {
      id: 30,
      title: 'Smart LED Light Bulb',
      price: 14.99,
      rating: 4.3,
      reviewsCount: 2100,
      category: 'Home Automation',
      image: 'https://picsum.photos/200?random=30',
      description:
        'Color-changing Wi-Fi bulb controllable via smartphone or voice.',
      prime: true,
      discount: 5,
    },
    {
      id: 31,
      title: 'Sports Water Bottle 1L',
      price: 14.99,
      rating: 4.4,
      reviewsCount: 1150,
      category: 'Sports & Fitness',
      image: 'https://picsum.photos/200?random=31',
      description:
        'Leakproof water bottle with flip-top lid for gym or travel.',
      prime: true,
      discount: 6,
    },
    {
      id: 32,
      title: 'Kids’ Building Blocks Set',
      price: 39.99,
      rating: 4.8,
      reviewsCount: 980,
      category: 'Toys',
      image: 'https://picsum.photos/200?random=32',
      description: 'Educational 100-piece block set for kids aged 3 and above.',
      prime: true,
      discount: 10,
    },
    {
      id: 33,
      title: 'Electric Hair Trimmer',
      price: 29.99,
      rating: 4.4,
      reviewsCount: 870,
      category: 'Personal Care',
      image: 'https://picsum.photos/200?random=33',
      description: 'Rechargeable trimmer with multiple cutting lengths.',
      prime: true,
      discount: 9,
    },
    {
      id: 34,
      title: 'Women’s Yoga Pants',
      price: 27.99,
      rating: 4.5,
      reviewsCount: 640,
      category: 'Fashion',
      image: 'https://picsum.photos/200?random=34',
      description:
        'Stretchy and comfortable yoga pants for workouts or lounging.',
      prime: true,
      discount: 10,
    },
    {
      id: 35,
      title: 'Smartphone Tripod Stand',
      price: 22.99,
      rating: 4.3,
      reviewsCount: 560,
      category: 'Accessories',
      image: 'https://picsum.photos/200?random=35',
      description: 'Adjustable tripod stand compatible with all smartphones.',
      prime: true,
      discount: 7,
    },
    {
      id: 36,
      title: 'Wireless Doorbell Kit',
      price: 29.99,
      rating: 4.4,
      reviewsCount: 480,
      category: 'Home Automation',
      image: 'https://picsum.photos/200?random=36',
      description:
        'Long-range wireless doorbell with 36 chimes and LED indicator.',
      prime: true,
      discount: 8,
    },
    {
      id: 37,
      title: 'Men’s Leather Belt',
      price: 21.99,
      rating: 4.5,
      reviewsCount: 390,
      category: 'Fashion',
      image: 'https://picsum.photos/200?random=37',
      description: 'Classic leather belt suitable for formal and casual wear.',
      prime: false,
      discount: 5,
    },
    {
      id: 38,
      title: 'Camping Tent for 4 People',
      price: 149.99,
      rating: 4.6,
      reviewsCount: 670,
      category: 'Outdoors',
      image: 'https://picsum.photos/200?random=38',
      description: 'Waterproof camping tent with quick setup design.',
      prime: true,
      discount: 20,
    },
    {
      id: 39,
      title: 'Microwave Oven 20L',
      price: 119.99,
      rating: 4.5,
      reviewsCount: 540,
      category: 'Home Appliances',
      image: 'https://picsum.photos/200?random=39',
      description: 'Compact microwave with defrost and multiple cooking modes.',
      prime: true,
      discount: 15,
    },
    {
      id: 40,
      title: 'LED Desk Lamp with USB Port',
      price: 34.99,
      rating: 4.4,
      reviewsCount: 720,
      category: 'Home & Office',
      image: 'https://picsum.photos/200?random=40',
      description:
        'Dimmable LED desk lamp with flexible neck and touch controls.',
      prime: true,
      discount: 10,
    },
    {
      id: 41,
      title: 'Wireless Security Door Sensor',
      price: 19.99,
      rating: 4.3,
      reviewsCount: 460,
      category: 'Home Automation',
      image: 'https://picsum.photos/200?random=41',
      description: 'Smart door sensor that alerts your phone when triggered.',
      prime: true,
      discount: 6,
    },
    {
      id: 42,
      title: 'Mini Projector 1080p',
      price: 159.99,
      rating: 4.4,
      reviewsCount: 890,
      category: 'Electronics',
      image: 'https://picsum.photos/200?random=42',
      description: 'Compact projector with HD display for home theater setup.',
      prime: true,
      discount: 18,
    },
    {
      id: 43,
      title: 'Travel Duffel Bag',
      price: 44.99,
      rating: 4.5,
      reviewsCount: 640,
      category: 'Accessories',
      image: 'https://picsum.photos/200?random=43',
      description:
        'Spacious duffel bag ideal for travel, gym, or weekend trips.',
      prime: true,
      discount: 9,
    },
    {
      id: 44,
      title: 'Men’s Running Shoes',
      price: 69.99,
      rating: 4.4,
      reviewsCount: 920,
      category: 'Fashion',
      image: 'https://picsum.photos/200?random=44',
      description:
        'Breathable and durable running shoes for everyday training.',
      prime: true,
      discount: 12,
    },
    {
      id: 45,
      title: 'Wireless Earbuds Pro',
      price: 119.99,
      rating: 4.7,
      reviewsCount: 2800,
      category: 'Electronics',
      image: 'https://picsum.photos/200?random=45',
      description:
        'Premium earbuds with noise cancellation and long battery life.',
      prime: true,
      discount: 15,
    },
    {
      id: 46,
      title: 'Electric Toothbrush Set',
      price: 39.99,
      rating: 4.6,
      reviewsCount: 700,
      category: 'Personal Care',
      image: 'https://picsum.photos/200?random=46',
      description: 'Rechargeable toothbrush with 5 brushing modes and 2 heads.',
      prime: true,
      discount: 10,
    },
    {
      id: 47,
      title: 'Non-slip Yoga Mat',
      price: 25.99,
      rating: 4.5,
      reviewsCount: 1100,
      category: 'Sports & Fitness',
      image: 'https://picsum.photos/200?random=47',
      description: 'Eco-friendly yoga mat with extra cushioning for comfort.',
      prime: true,
      discount: 7,
    },
    {
      id: 48,
      title: 'Women’s Sunglasses',
      price: 29.99,
      rating: 4.3,
      reviewsCount: 560,
      category: 'Fashion',
      image: 'https://picsum.photos/200?random=48',
      description: 'Stylish UV-protected sunglasses with gradient lenses.',
      prime: true,
      discount: 8,
    },
    {
      id: 49,
      title: 'Bluetooth Car Adapter',
      price: 19.99,
      rating: 4.4,
      reviewsCount: 820,
      category: 'Automotive',
      image: 'https://picsum.photos/200?random=49',
      description: 'Stream music and take hands-free calls in your car easily.',
      prime: true,
      discount: 10,
    },
    {
      id: 50,
      title: 'Laptop Cooling Pad',
      price: 34.99,
      rating: 4.5,
      reviewsCount: 690,
      category: 'Electronics',
      image: 'https://picsum.photos/200?random=50',
      description:
        'Dual-fan cooling pad compatible with laptops up to 17 inches.',
      prime: true,
      discount: 12,
    },
    {
      id: 51,
      name: 'Rolex Submariner',
      brand: 'Rolex',
      description:
        'Luxury diving watch with 300m water resistance and timeless design.',
      price: 8999,
      discount: 10,
      category: 'Female',
      stock: 5,
      rating: 3.5,
      colors: ['Silver', 'Black', 'Gold'],
      isFeatured: true,
      image:
        '//currenwatches.com.pk/cdn/shop/products/Untitled-1copy.jpg?v=1750833325&amp;width=165 165w,//currenwatches.com.pk/cdn/shop/products/Untitled-1copy.jpg?v=1750833325&amp;width=360 360w,//currenwatches.com.pk/cdn/shop/products/Untitled-1copy.jpg?v=1750833325&amp;width=493 493w',
    },
    {
      id: 52,
      name: 'Omega Speedmaster',
      brand: 'Omega',
      description:
        'The Moonwatch, worn during NASA missions. Legendary chronograph.',
      price: 7599,
      discount: 5,
      category: 'Male',
      stock: 3,
      rating: 4.8,
      colors: ['Black', 'Blue'],
      isFeatured: true,
      image:
        '//currenwatches.com.pk/cdn/shop/products/73fe8cb383af0b5ca132558ab84c0c8b.jpg?v=1757597303&amp;width=165 165w,//currenwatches.com.pk/cdn/shop/products/73fe8cb383af0b5ca132558ab84c0c8b.jpg?v=1757597303&amp;width=360 360w,//currenwatches.com.pk/cdn/shop/products/73fe8cb383af0b5ca132558ab84c0c8b.jpg?v=1757597303&amp;width=493 493w',
    },
    {
      id: 53,
      name: 'Tag Heuer Carrera',
      brand: 'Tag Heuer',
      description:
        'Racing-inspired chronograph with sporty and stylish design.',
      price: 5499,
      discount: 0,
      category: 'Female',
      stock: 7,
      rating: 4.6,
      colors: ['Black', 'Silver'],
      isFeatured: false,
      image:
        '//currenwatches.com.pk/cdn/shop/products/Untitled-2copy_512dcfe9-2fc0-42f9-a47b-f8743958e39e.jpg?v=1645790849&amp;width=165 165w,//currenwatches.com.pk/cdn/shop/products/Untitled-2copy_512dcfe9-2fc0-42f9-a47b-f8743958e39e.jpg?v=1645790849&amp;width=360 360w,//currenwatches.com.pk/cdn/shop/products/Untitled-2copy_512dcfe9-2fc0-42f9-a47b-f8743958e39e.jpg?v=1645790849&amp;width=493 493w',
    },
    {
      id: 54,
      name: 'Seiko Prospex',
      brand: 'Seiko',
      description:
        'Affordable diving watch with automatic movement and strong durability.',
      price: 699,
      discount: 15,
      category: 'Unisex',
      stock: 56,
      rating: 4.5,
      colors: ['Blue', 'Black', 'Green'],
      isFeatured: false,
      image: '/src/assets/images/watch (1).jpg',
    },
    {
      id: 55,
      name: 'Casio G-Shock',
      brand: 'Casio',
      description: 'Shock-resistant sports watch with rugged durability.',
      price: 9000,
      discount: 0,
      category: 'Male',
      stock: 20,
      rating: 4.4,
      colors: ['Black', 'Red', 'Green'],
      isFeatured: true,
      items: [
        {
          name: 'Jeans under $50',
          image: 'https://picsum.photos/150/150?random=2',
        },
        {
          name: 'Tops under $25',
          image: 'https://picsum.photos/150/150?random=3',
        },
        {
          name: 'Dresses under $30',
          image: 'https://picsum.photos/150/150?random=4',
        },
        {
          name: 'Shoes under $50',
          image: 'https://picsum.photos/150/150?random=5',
        },
      ],
    },
    {
      id: 56,
      name: 'Audemars Piguet Royal Oak',
      brand: 'Audemars Piguet',
      description:
        'Iconic luxury watch with octagonal bezel and premium craftsmanship.',
      price: 29999,
      discount: 8,
      category: 'Female',
      stock: 2,
      rating: 5.0,
      colors: ['Silver', 'Gold'],
      isFeatured: true,
      image:
        '//currenwatches.com.pk/cdn/shop/files/1b4f8b28-4002-4d0a-be2b-218f3fa6e330.jpg?v=1747820666&amp;width=165 165w,//currenwatches.com.pk/cdn/shop/files/1b4f8b28-4002-4d0a-be2b-218f3fa6e330.jpg?v=1747820666&amp;width=360 360w,//currenwatches.com.pk/cdn/shop/files/1b4f8b28-4002-4d0a-be2b-218f3fa6e330.jpg?v=1747820666&amp;width=493 493w',
    },
    {
      id: 57,
      name: 'Patek Philippe Nautilus',
      brand: 'Patek Philippe',
      description: 'Prestigious Swiss luxury sports watch with unique style.',
      price: 49999,
      discount: 12,
      category: 'Male',
      stock: 1,
      rating: 5.0,
      colors: ['Silver', 'Blue'],
      isFeatured: true,
      image:
        '//currenwatches.com.pk/cdn/shop/products/73fe8cb383af0b5ca132558ab84c0c8b.jpg?v=1757597303&amp;width=165 165w,//currenwatches.com.pk/cdn/shop/products/73fe8cb383af0b5ca132558ab84c0c8b.jpg?v=1757597303&amp;width=360 360w,//currenwatches.com.pk/cdn/shop/products/73fe8cb383af0b5ca132558ab84c0c8b.jpg?v=1757597303&amp;width=493 493w',
    },
    {
      id: 58,
      name: 'Breitling Navitimer',
      brand: 'Breitling',
      description: 'Pilot’s watch with slide rule bezel for aviation lovers.',
      price: 6599,
      discount: 0,
      category: 'Male',
      stock: 4,
      rating: 4.7,
      colors: ['Black', 'Brown'],
      isFeatured: false,
      image: '/src/assets/images/watch (4).jpg',
    },
    {
      id: 59,
      name: 'Cartier Santos',
      brand: 'Cartier',
      description: 'Elegant square watch with rich history of aviation.',
      price: 8999,
      discount: 6,
      category: 'Female',
      stock: 6,
      rating: 4.8,
      colors: ['Rose Gold', 'Silver'],
      isFeatured: true,
      image: '/src/assets/images/watch (5).jpg',
    },
    {
      id: 60,
      name: 'Tissot PRX',
      brand: 'Tissot',
      description: 'Affordable Swiss watch with integrated bracelet design.',
      price: 499,
      discount: 10,
      category: 'Female',
      stock: 15,
      rating: 4.5,
      colors: ['Silver', 'Black', 'Blue'],
      isFeatured: false,
      image: '/src/assets/images/watch (6).jpg',
    },

    {
      id: 61,
      name: 'Longines HydroConquest',
      brand: 'Longines',
      description: 'Swiss diving watch with ceramic bezel and sleek design.',
      price: 1299,
      discount: 7,
      category: 'Male',
      stock: 8,
      rating: 4.6,
      colors: ['Black', 'Blue'],
      isFeatured: false,
      image: '/src/assets/images/watch (8).jpg',
    },
    {
      id: 62,
      name: 'Hublot Big Bang',
      brand: 'Hublot',
      description: 'Bold luxury sports watch with innovative design.',
      price: 15999,
      discount: 5,
      category: 'Female',
      stock: 3,
      rating: 4.9,
      colors: ['Black', 'Gold'],
      isFeatured: true,
      image:
        '//currenwatches.com.pk/cdn/shop/products/S38f7a029e54b47c1a5d68f068c54bd97Y.jpg?v=1747630736&amp;width=165 165w,//currenwatches.com.pk/cdn/shop/products/S38f7a029e54b47c1a5d68f068c54bd97Y.jpg?v=1747630736&amp;width=360 360w,//currenwatches.com.pk/cdn/shop/products/S38f7a029e54b47c1a5d68f068c54bd97Y.jpg?v=1747630736&amp;width=493 493w',
    },
    {
      id: 63,
      name: 'IWC Pilot’s Watch',
      brand: 'IWC',
      description: 'Classic aviation-inspired timepiece for professionals.',
      price: 7999,
      discount: 0,
      category: 'Male',
      stock: 5,
      rating: 4.7,
      colors: ['Black', 'Brown'],
      isFeatured: false,
      image: '/src/assets/images/watch (9).jpg',
    },
    {
      id: 64,
      name: 'Fossil Grant',
      brand: 'Fossil',
      description: 'Stylish fashion chronograph at an affordable price.',
      price: 249,
      discount: 20,
      category: 'Female',
      stock: 18,
      rating: 4.3,
      colors: ['Blue', 'Brown', 'Rose Gold'],
      isFeatured: false,
      image: '/src/assets/images/watch (4).jpg',
    },
    {
      id: 65,
      name: 'Citizen Eco-Drive',
      brand: 'Citizen',
      description: 'Eco-friendly solar-powered watch with long battery life.',
      price: 399,
      discount: 15,
      category: 'Unisex',
      stock: 12,
      rating: 4.6,
      colors: ['Black', 'Green', 'Silver'],
      isFeatured: true,
      image: '/src/assets/images/watch (8).jpg',
    },
  ],
}

const productsSlice = createSlice({
  name: 'products',
  initialState: initial,
  reducers: {
    // Define your reducers
  },
})

export const productsReducer = productsSlice.reducer
export const {} = productsSlice.actions
